# Generated by Django 5.0.6 on 2024-05-18 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('min_trip_duration', models.IntegerField()),
                ('max_trip_duration', models.IntegerField()),
                ('weather_condition', models.CharField(max_length=50)),
                ('terrain_type', models.CharField(max_length=50)),
                ('gear_image', models.ImageField(upload_to='gear_images/')),
            ],
        ),
    ]
