# Generated by Django 5.0.6 on 2024-05-21 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gear',
            name='gear_image',
            field=models.ImageField(blank=True, null=True, upload_to='gear_images/'),
        ),
    ]
